{% set name = "chemex" %}
{% set version = "2025.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chemex-{{ version }}.tar.gz
  sha256: a55618f2eafc3dd933ef9f4db21eeccb4c5aa0f5f6c09d14a2948d8a06978382

build:
  entry_points:
    - chemex = chemex.chemex:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12
    - hatchling
    - uv-dynamic-versioning
    - pip
  run:
    - python >=3.12
    - annotated-types >=0.7.0
    - cachetools >=5.5.1
    - emcee >=3.1.6
    - lmfit >=1.3.2
    - matplotlib-base >=3.10.0
    - numdifftools >=0.9.41
    - numpy >=2.2.3
    - pydantic >=2.10.6
    - rapidfuzz >=3.12.1
    - rich >=13.9.4
    - scipy >=1.15.2

test:
  imports:
    - chemex
  commands:
    - pip check
    - chemex --help
  requires:
    - pip

about:
  summary: An analysis program for chemical exchange detected by NMR
  license: GPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gbouvignies