{% set name = "chemex" %}
{% set version = "2018.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gbouvignies/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c60b5d7e880eb62264e7c3755a7df68e9d6ad802185b3b6084e155826de556c5

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
      - chemex = chemex.chemex:main

requirements:
  host:
    - python>=3.5
    - setuptools
    - pip
  run:
    - python>=3.5
    - numpy
    - scipy
    - matplotlib-base
    - lmfit
    - asteval

test:
  imports:
    - chemex

about:
  home: http://github.com/gbouvignies/chemex
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'ChemEx is an analysis program for chemical exchange detected by NMR.'
  description: |
      ChemEx is an analysis program for chemical exchange detected by NMR.
      It is designed to take almost any kind of NMR data to aid the analysis,
      but the principle techniques are CPMG relaxation dispersion and Chemical
      Exchange Saturation Transfer.
  dev_url: https://github.com/gbouvignies/chemex

extra:
  recipe-maintainers:
    - gbouvignies
