{% set name = "chemex" %}
{% set version = "2023.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemex-{{ version }}.tar.gz
  sha256: 91a4e9f4133a74bc50fec793a3980c1dfbfda292e7875504b6f62d13f2e29faf

build:
  entry_points:
    - chemex = chemex.chemex:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pdm-backend
    - pip
  run:
    - python >=3.10
    - numpy >=1.25.0
    - scipy >=1.9.3
    - matplotlib-base >=3.7.1
    - lmfit >=1.2.1
    - pydantic >=2.0.1
    - cachetools >=5.3.1
    - rich >=13.4.2
    - tomli >=2.0.1
    - rapidfuzz >=3.1.1

test:
  imports:
    - chemex
  commands:
    - pip check
    - chemex --help
  requires:
    - pip

about:
  home: http://gbouvignies.github.io/ChemEx/
  summary: An analysis program for chemical exchange detected by NMR
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gbouvignies
