{% set name = "chemex" %}
{% set version = "2024.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemex-{{ version }}.tar.gz
  sha256: 29b9c3c2522d30e2c3be5dbedf691c544d42d2fc1db3546092a30749c72dfbbd

build:
  entry_points:
    - chemex = chemex.chemex:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - pdm-backend
    - pip
  run:
    - python >=3.10,<3.13
    - numpy >=1.26.1
    - scipy >=1.11.3
    - matplotlib-base >=3.8.0
    - lmfit >=1.2.2
    - pydantic >=2.4.2
    - cachetools >=5.3.2
    - rich >=13.6.0
    - tomli >=2.0.1
    - rapidfuzz >=3.4.0
    - emcee >=3.1.4

test:
  imports:
    - chemex
  commands:
    - pip check
    - chemex --help
  requires:
    - pip

about:
  home: http://gbouvignies.github.io/ChemEx/
  summary: An analysis program for chemical exchange detected by NMR
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gbouvignies
