{% set python_min = '3.11' %}
{% set name = "chemex" %}
{% set version = "2024.9.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chemex-{{ version }}.tar.gz
  sha256: a06f1fc8a4f7cb6a16ff368071fba2d391b1407a1ccf0d54318ea7ba1836278e

build:
  entry_points:
    - chemex = chemex.chemex:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }},<3.13
    - numpy >=1.26.1
    - scipy >=1.11.3
    - matplotlib-base >=3.8.0
    - lmfit >=1.2.2
    - pydantic >=2.4.2
    - cachetools >=5.3.2
    - rich >=13.6.0
    - rapidfuzz >=3.4.0
    - emcee >=3.1.4
    - numdifftools >=0.9.41
    - annotated-types >=0.6.0

test:
  imports:
    - chemex
  commands:
    - pip check
    - chemex --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://gbouvignies.github.io/ChemEx/
  summary: An analysis program for chemical exchange detected by NMR
  license: GPL-3.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gbouvignies
