{% set name = "chemex" %}
{% set version = "2024.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemex-{{ version }}.tar.gz
  sha256: 5d2d8459579b65dba02cedac767e39c7c905b570adf97016086575d7c1422c65

build:
  entry_points:
    - chemex = chemex.chemex:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11,<3.13
    - pdm-backend
    - pip
  run:
    - python >=3.11,<3.13
    - numpy >=1.26.1
    - scipy >=1.11.3
    - matplotlib-base >=3.8.0
    - lmfit >=1.2.2
    - pydantic >=2.4.2
    - cachetools >=5.3.2
    - rich >=13.6.0
    - rapidfuzz >=3.4.0
    - emcee >=3.1.4
    - numdifftools >=0.9.41
    - annotated-types >=0.6.0

test:
  imports:
    - chemex
  commands:
    - pip check
    - chemex --help
  requires:
    - pip

about:
  home: http://gbouvignies.github.io/ChemEx/
  summary: An analysis program for chemical exchange detected by NMR
  license: GPL-3.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gbouvignies
